#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import sys
from functools import wraps
import colorlog
import os
from datetime import datetime


def setup_logging(log_dir='log/', log_file=None, level="INFO"):
    """
    Set up logging: colored output on console, plain text in file.

    Args:
        log_dir (str): Directory for log files.
        log_file (str): Log file name. If None, auto-generated by timestamp.
        level (str): Log level ('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL').
    """
    numeric_level = getattr(logging, level.upper(), None)
    if not isinstance(numeric_level, int):
        print(f"Warning: Invalid log level '{level}'. Defaulting to 'INFO'.")
        numeric_level = logging.INFO

    if not os.path.exists(log_dir):
        os.makedirs(log_dir, exist_ok=True)

    if log_file:
        log_file = os.path.join(log_dir, log_file)
    else:
        log_file = os.path.join(
            log_dir, f"log_{datetime.now().strftime('%Y-%m-%d-%H-%M-%S')}.log"
        )

    # Root logger
    logger = logging.getLogger()
    logger.setLevel(numeric_level)

    # Clear old handlers to avoid duplicates
    if logger.hasHandlers():
        logger.handlers.clear()

    # File handler (no color)
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(numeric_level)
    file_formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
    )
    file_handler.setFormatter(file_formatter)

    # Console handler (colored)
    console_handler = colorlog.StreamHandler(stream=sys.stdout)
    console_handler.setLevel(numeric_level)
    console_formatter = colorlog.ColoredFormatter(
        "%(log_color)s%(asctime)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s",
        log_colors={
            "DEBUG": "bold_black",
            "INFO": "white",
            "WARNING": "yellow",
            "ERROR": "red",
            "CRITICAL": "red,bg_white",
        },
    )
    console_handler.setFormatter(console_formatter)

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)


def get_logger(func):
    """Decorator that injects a named logger as the first argument."""
    @wraps(func)
    def wrapper(*args, **kwargs):
        logger_name = f"{func.__module__}.{func.__name__}"
        logger = logging.getLogger(logger_name)
        return func(logger, *args, **kwargs)
    return wrapper


def color_message(message, color='cyan'):
    """Add color to a log message string."""
    colored_message = colorlog.ColoredFormatter(
        "%(log_color)s%(message)s",
        log_colors={
            'DEBUG': 'cyan',
            'INFO': color,
            'WARNING': 'yellow',
            'ERROR': 'red',
            'CRITICAL': 'bold_red',
        }
    ).format(logging.makeLogRecord({'msg': message, 'levelname': 'INFO', 'levelno': logging.INFO}))
    return colored_message